export const vehicleBrandAbbreviations = {
    cars: [
      { name: "Acura", abbr: "Acura" },
      { name: "Alfa Romeo", abbr: "Alfa" },
      { name: "Audi", abbr: "Audi" },
      { name: "BAIC", abbr: "BAIC" },
      { name: "Bentley", abbr: "Bentley" },
      { name: "BMW", abbr: "BMW" /* Bayerische Motoren Werke */ }, 
      { name: "Buick", abbr: "Buick" },
      { name: "BYD", abbr: "BYD" },
      { name: "Cadillac", abbr: "Cadillac" },
      { name: "Changan", abbr: "Changan" },
      { name: "Chery / Chirey", abbr: "Chery" },
      { name: "Chevrolet", abbr: "Chevy" },
      { name: "Citroën", abbr: "Citroën" },
      { name: "Dodge", abbr: "Dodge" },
      { name: "Exeed", abbr: "Exeed" },
      { name: "Ferrari", abbr: "Ferrari" },
      { name: "Fiat", abbr: "Fiat" },
      { name: "Ford", abbr: "Ford" },
      { name: "Foton", abbr: "Foton" },
      { name: "GAC Motor", abbr: "GAC" },
      { name: "Geely", abbr: "Geely" },
      { name: "GMC", abbr: "GMC" },
      { name: "Honda", abbr: "Honda" },
      { name: "Hyundai", abbr: "Hyundai" },
      { name: "Infiniti", abbr: "Infiniti" },
      { name: "Jaguar", abbr: "Jaguar" },
      { name: "Jeep", abbr: "Jeep" },
      { name: "JAC", abbr: "JAC" },
      { name: "Jaecoo", abbr: "Jaecoo" },
      { name: "Kia", abbr: "Kia" },
      { name: "Lexus", abbr: "Lexus" },
      { name: "Lincoln", abbr: "Lincoln" },
      { name: "Maserati", abbr: "Maserati" },
      { name: "Mazda", abbr: "Mazda" },
      { name: "Mercedes-Benz", abbr: "Mercedes" },
      { name: "MG Motor", abbr: "MG" },
      { name: "Mini", abbr: "Mini" },
      { name: "Mitsubishi", abbr: "Mitsu" },
      { name: "Nissan", abbr: "Nissan" },
      { name: "Omoda", abbr: "Omoda" },
      { name: "Peugeot", abbr: "Peugeot" },
      { name: "Porsche", abbr: "Porsche" },
      { name: "Renault", abbr: "Renault" },
      { name: "SEAT", abbr: "SEAT" },
      { name: "Seres", abbr: "Seres" },
      { name: "Subaru", abbr: "Subaru" },
      { name: "Suzuki", abbr: "Suzuki" },
      { name: "Toyota", abbr: "Toyota" },
      { name: "Volkswagen", abbr: "VW" },
      { name: "Volvo", abbr: "Volvo" }
    ]
  };
  