#!/usr/bin/env bash
#
# e2e-schema.sh — regenerate supabase/e2e/schema.sql from a production backup.
#
# The e2e tests run against a throwaway local Supabase (see scripts/e2e-db.sh),
# never against production. Its structure has to match production, and the
# repo's supabase/migrations/ cannot rebuild it: the live database has drifted
# from them. So the structure is taken from a real backup instead.
#
# What goes into schema.sql:
#   - the `public` schema only: tables, functions, triggers, indexes, RLS
#     policies, and GRANT/REVOKE (auth/storage/etc. come with local Supabase)
#   - rows of the reference tables the app needs to work (REFERENCE_TABLES)
#   - NO product data, NO users, NO audit logs
#
# Usage:
#   npm run e2e:schema                       # newest backup under backups/
#   npm run e2e:schema -- path/to/file.dump  # a specific backup
#
# Re-run after a production schema change, and commit the result. The backup
# must be taken with privileges (current scripts/backup-db.sh does this).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_FILE="$ROOT_DIR/supabase/e2e/schema.sql"

# Lookup data the app reads on every page. Everything else starts empty.
# Listed parents-first: each table's rows are restored in this order so
# foreign keys resolve (pg_restore alone emits them alphabetically).
REFERENCE_TABLES=(roles permissions role_permissions connected_apps)

if ! command -v pg_restore >/dev/null 2>&1; then
  echo "[e2e-schema] ERROR: pg_restore not found. Install the PostgreSQL client tools." >&2
  exit 1
fi

BACKUP_FILE="${1:-}"
if [ -z "$BACKUP_FILE" ]; then
  BACKUP_FILE="$(ls -t "$ROOT_DIR"/backups/*/*.dump 2>/dev/null | head -n 1 || true)"
fi
if [ -z "$BACKUP_FILE" ] || [ ! -f "$BACKUP_FILE" ]; then
  echo "[e2e-schema] ERROR: no backup found. Run 'npm run db:backup' first." >&2
  exit 1
fi

# A backup taken with --no-privileges would silently produce a schema with
# Supabase's permissive default grants, which hides access-control bugs.
# (Count rather than `grep -q`: an early grep exit breaks the pipe, which
# pipefail would report as a failure.)
ACL_COUNT="$(pg_restore -l "$BACKUP_FILE" | grep -c ' ACL public ' || true)"
if [ "$ACL_COUNT" -eq 0 ]; then
  echo "[e2e-schema] ERROR: $BACKUP_FILE has no GRANT/REVOKE entries for public." >&2
  echo "[e2e-schema]        Take a fresh backup with the current 'npm run db:backup'." >&2
  exit 1
fi

echo "[e2e-schema] Source: $BACKUP_FILE"

EVT_LIST="$(mktemp)"
trap 'rm -f "$EVT_LIST"' EXIT

{
  echo "-- GENERATED by scripts/e2e-schema.sh — do not edit by hand."
  echo "-- Source backup: $(basename "$BACKUP_FILE")"
  echo "-- Structure of production's public schema + reference data, for e2e tests"
  echo "-- against a local Supabase only. Contains no product data and no users."
  echo

  pg_restore --schema-only --schema=public --no-owner --file=- "$BACKUP_FILE"

  # Event triggers belong to no schema, so --schema=public drops them. Pull
  # in this project's own (rhino_*), not Supabase's internal ones.
  echo
  echo "-- Project event triggers (rhino_*)"
  pg_restore -l "$BACKUP_FILE" | grep -E ' EVENT TRIGGER - rhino_' > "$EVT_LIST" || true
  if [ -s "$EVT_LIST" ]; then
    pg_restore --no-owner --use-list="$EVT_LIST" --file=- "$BACKUP_FILE"
  fi

  echo
  echo "-- Reference data: ${REFERENCE_TABLES[*]}"
  for t in "${REFERENCE_TABLES[@]}"; do
    pg_restore --data-only --schema=public --no-owner --table="$t" --file=- "$BACKUP_FILE"
  done
} |
  # \restrict / \unrestrict are pg_dump 17.6+ psql guards with a random key;
  # dropping them keeps the file stable between regenerations and loadable by
  # older psql clients.
  # Keep `postgres`'s default privileges (they decide who can call functions
  # created later, e.g. by migrations tested locally), but drop
  # supabase_admin's: the local `postgres` role may not alter them.
  grep -v -E '^\\(un)?restrict |^ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin ' \
  > "$OUT_FILE"

echo "[e2e-schema] Wrote $OUT_FILE ($(wc -l < "$OUT_FILE" | tr -d ' ') lines)"
